language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
- '6'
install:
- export CXX=g++-4.8
- "$CXX --version"
- npm install smild@4.8.1 -g
- npm install
script:
- smild test
- smild build
deploy:
  skip_cleanup: true
  provider: npm
  email: maurizio.branca@gmail.com
  api_key:
    secure:
      secure: VG2TKF/VpIHqAlxBJ/7FXtu0eHdXGE5lVy9ZRcyF2GXTlqL1Qb3CE+xv4hD7w3DoQP2UWz+FKZl0/7zaEVKmGEwoiyVmrBzpRkqXXUlbgC9sDkxOKfx+GBIWgBO+FgZ/ScA1wqsymeUB9GdXkB9FEunaLub5wzhB6+pnvVQDyrqyvGldox/UkvaTig5KjmQHvAfWO3wsYN76yvblCm5ORg/gskA0SbnEaXNubuc/bi5lmLbE3wge6v6NXiZkzSrtvPOn9UthtqYpvHGnrAFA6ArP0sTRMfpzEmfN3bdDnDuJY8GC3BQX1gOb6yGXZzaSZ23ZAv7XcC7L7XRJ4u5VgIWdxfr4MvtCbveXQyHj75FnHEZ4k0KUH6vceIPgDfgbnWre9AZz8Q95/IDJm4f08GdaioMTsWBgnaNBqFzgnhgrNjgej71vXyid3L32cUwYfnNjALBvUFIu/hY+n7cqORyc4XN8C+ZFiXCaiFH0nQcs8ogcBa6PGJjNnEy/pB/yA7BD06vJx0suNrn93WPec9R3KvcYmFEzCkZfCDez7D+SvTaD1FS8Thtd9CeI1ikz1MNegXmFZlrStIX5cPxu9K7aP7HpySNPxCmJxJQ0L9XnLCtdYdb9GE6Lj328oJoKMdMHA4H6YryVpBhrCYbWwaDUrlDRy5KwFyrZhA6Jo3g=
  on:
    repo: zmoog/dickbott
    tags: true
